sudo: false
language: python
python:
    - "2.7"
    - "3.5"
    - "3.6"
install:
    - pip install tox-travis flake8
script:
    - tox
    - flake8 mappyfile --max-line-length=120
    - flake8 --ignore=E501 tests
