sudo: false
language: python
python:
    - "2.7"
    - "3.5"
    - "3.6"
    - "3.7-dev"
    - "pypy"
    - "pypy3"
install:
    - pip install -r requirements-dev.txt
    - pip install tox-travis flake8 coveralls
script:
    - tox
    - coverage run --source mappyfile -m py.test
    - coverage report -m

after_success:
    - coveralls