sudo: false
language: python
python:
    - "2.7"
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8-dev"
    - "pypy"
    - "pypy3"
install:
    - pip install tox-travis coveralls
script:
    - tox
    #- coverage run --source mappyfile -m py.test
    #- coverage report -m

after_success:
    - coveralls